### ISSUE TITLE
Option to disable Changing Inverter Charger modes.

### ISSUE THREAD

**Issue by Metamba** [victronenergy/venus-html5-app#105]
It may be  good to have the option of disabling the changing of the Inverter Charger mode via the HTML5 app. This may prevent mistakenly changing the inverter mode.

**Comment by martinbosma** [comment]
@AlexImb Can you post your suggestion, so we can discuss it here?
@mpvader What do you think about this?

**Comment by AlexImb** [comment]
My suggestion is to add a lock icon at the top that disables all the buttons in the app. It can be unlocked by default, so only users that think is very likely to accidentally touch the buttons can enable it. The state can be stored in `localStorage` to be persistent for across multiple sessions on the same device. 

![image](https://user-images.githubusercontent.com/4534299/80508396-47afb600-8978-11ea-8d4e-042e8ae09de6.png)

**Comment by AlexImb** [comment]
We looked into making this more intuitive and easier to use. We considered the idea of tapping and holding to change the state of a widget but we defaulted to the lock icon. Considering the space available on some devices and the fact that the app can also be used on devices without touchscreen makes is hard to indicate that you have to hold the button. 

So the new design proposal is:

![image](https://user-images.githubusercontent.com/4534299/93086179-030e8800-f697-11ea-967d-65378991501e.png)

![image](https://user-images.githubusercontent.com/4534299/93086210-128dd100-f697-11ea-871c-9c15b091124f.png)

**Comment by mpvader** [comment]
ok! (but make sure contrast is good enough, on the lower image contrast is really bad, and it was already not too good

**Comment by AlexImb** [comment]
> ok! (but make sure contrast is good enough, on the lower image contrast is really bad, and it was already not too good

Yes, we'll also look into improving the disabled state for buttons in general as well.

**Comment by AlexImb** [comment]
#153 implements the proposed solution for this issue and the improved contrast ratio for the disabled buttons:

![image](https://user-images.githubusercontent.com/4534299/94699440-9a800600-033a-11eb-9708-25c2f4850a0f.png)

![image](https://user-images.githubusercontent.com/4534299/94699382-8cca8080-033a-11eb-82d3-b070ffd1d447.png)

![image](https://user-images.githubusercontent.com/4534299/94699854-17ab7b00-033b-11eb-9564-1f4333add672.png)

![image](https://user-images.githubusercontent.com/4534299/94699581-c1d6d300-033a-11eb-8e76-b72a394b0aa3.png)
![image](https://user-images.githubusercontent.com/4534299/94699633-d31fdf80-033a-11eb-9ed9-326887969ac1.png)

**Comment by AlexImb** [comment]
@thlassche this functionality together with the combined generator metrics + controls (https://github.com/victronenergy/venus-html5-app/issues/142) and the 3A input limit (https://github.com/victronenergy/venus-html5-app/pull/152) are on the `develop` branch and planned to be included in the Venus v2.70 release.

**Comment by AlexImb** [comment]
Included in 1.7.0
