### ISSUE TITLE
Raymarine home icon occludes Victron logo

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#108]
![Axiom 19 XL](https://user-images.githubusercontent.com/6614648/64862077-eb3e9700-d631-11e9-99cd-9ac7b39f3b6e.JPG)

**Comment by AlexImb** [comment]
Some possible solutions for this are:

1. Center the logo
![image](https://user-images.githubusercontent.com/4534299/71368356-06616100-25a8-11ea-94fd-e69096a9dabd.png)

2. Increase the vertical padding which probably does not look as good for other types of MFDs and split screens

**Comment by mpvader** [comment]
Hi Alex, 👍 on all the fixes. For this one, centering that logo is quite disturbing the design, no?

**Comment by martinbosma** [comment]
Agree. How about left aligning it with the left column in a similar way the remote console button is aligned on the rhs?
Don't know how that will work out in case of a single column and/or small resolution.

**Comment by thlassche** [comment]
Agree with @martinbosma, @AlexImb can you make a screenshot of how that looks?

**Comment by AlexImb** [comment]
W: 320
![image](https://user-images.githubusercontent.com/4534299/71515989-aa982000-28a6-11ea-93c0-5d5b55a43c56.png)

W: 500
![image](https://user-images.githubusercontent.com/4534299/71515893-2776ca00-28a6-11ea-854f-dab8778bd55a.png)

W: 768
![image](https://user-images.githubusercontent.com/4534299/71515920-512ff100-28a6-11ea-991a-7cb64d31340b.png)

W: 1024
![image](https://user-images.githubusercontent.com/4534299/71516029-f054e880-28a6-11ea-8563-0bd2765d1712.png)

W: 2056+ 
![image](https://user-images.githubusercontent.com/4534299/71516050-0b275d00-28a7-11ea-9420-72bca9c9b7df.png)

**Comment by thlassche** [comment]
Looks good to me. 

@mpvader @martinbosma do you happen to know if the Raymarine devices also has resizable widgets? I.e.: can it happen that the Home icon still occludes the Victron logo if there is a small configuration chosen on the Raymarine?

**Comment by AlexImb** [comment]
From looking at their website it looks like they do and can even render more buttons on the top-left next to the home one. That's the reason I initially suggested the central logo. 

However, the current solution should reduce the cases when this happens. If there are still cases when it occurs then increasing the top padding will definitely fix it.

**Comment by martinbosma** [comment]
Looking good! Afaik, the Raymarine MFDs only have full screen widgets. Perhaps in the future they will have split screens/smaller screen configurations.

Hower, the other brands do support smaller configurations. The Navico brands also can have buttons in the corners, see pic.
![Simrad-NSS-12-evo-3-ssbilbehor_se](https://user-images.githubusercontent.com/6614648/71531123-8e6ba180-28ed-11ea-9880-9ea0d83f25bc.jpg)

**Comment by martinbosma** [comment]
@AlexImb I think this needs some more thinking/work. Below a picture of a 12" Raymarine MFD; the initial issue was with a much bigger screen. 

I also noticed that the top left button on a Simrad is also overlapping the Victron icon; see above for the Simrad layout. I think this applies to all Navico brands.

Perhaps we can add more top padding?

![image](https://user-images.githubusercontent.com/6614648/85514865-c59ce000-b5fc-11ea-925b-2992a1cfed59.png)

**Comment by AlexImb** [comment]
Fix included in Release 1.4.2.

**Comment by AlexImb** [comment]
![image](https://user-images.githubusercontent.com/4534299/85534884-ffc4ac80-b611-11ea-8f7b-b1c2be0efd7e.png)
