### ISSUE TITLE
Automatically disable on/off/charger only control

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus-html5-app#109]
For systems in which that feature doesnt exist (vebus bms)

**Comment by martinbosma** [comment]
It should already be disabled based on `/ModeIsAdjustable`, see [here](https://github.com/victronenergy/venus-html5-app/blob/master/src/app/components/InverterCharger/InverterCharger.js#L64). Or do you want to hide it?

**Comment by mpvader** [comment]
I made that issue following a complaint (from Gary) that that doesnt work. I’ll tell him that it should work and update fw etc.

**Comment by mpvader** [comment]
Or perhaps the issue is indeed to hide it. Or make it more info like & less button like

**Comment by AlexImb** [comment]
Current state using simulation M from [venus-docker](https://github.com/victronenergy/venus-docker):

`Message received: N/0242ac110002/vebus/257/ModeIsAdjustable - {"value": 0}`

![image](https://user-images.githubusercontent.com/4534299/80501189-6e1d2380-896f-11ea-85ca-d7b211bad2ac.png)

For other values: 

![image](https://user-images.githubusercontent.com/4534299/80501735-129f6580-8970-11ea-91a7-35063eab55db.png)

**Comment by marcoemanuelecocco** [comment]
in my camper the inverter is installed inside the cabin and the hum of the transformer can be heard at night. 
 It would be a great idea if you could program the times when the inverter can be turned off, only chargers, only inverters.
  A bar graph with 24 hours divided into 30-minute sections would be enough and for each section you could choose the option: off, charger, inverter

**Comment by martinbosma** [comment]
> in my camper the inverter is installed inside the cabin and the hum (noise) of the transformer can be heard at night.
> It would be a great idea if you could program the times when the inverter can be turned off, only chargers, only inverters.
> A bar graph with 24 hours divided into 30-minute sections would be enough and for each section you could choose the option: off, charger, inverter

@marcoemanuelecocco Thank you for your suggestion, but I don't think this is as easy as it sounds as it also requires changes to the Venus operation system. Did you know that you can show the app on your phone/tablet as well? If you browse to `http://<ip address of the GX device>/app` or `http://venus.local/app` you can control the inverter from your bed ;).

**Comment by marcoemanuelecocco** [comment]
Yes i make the control with a Raspberry and a simple LCD resistive 7"
monitor

Il Ven 10 Lug 2020, 08:38 Martin Bosma <notifications@github.com> ha
scritto:

**Comment by AlexImb** [comment]
#151 solves this by hiding the buttons when `/ModeIsAdjustable` is 0 and adds the mode in the subtitle:

Before:

![image](https://user-images.githubusercontent.com/4534299/93592914-58a6a580-f9b3-11ea-9887-61e54820de22.png)

After: 

![image](https://user-images.githubusercontent.com/4534299/93592728-fea5e000-f9b2-11ea-871f-54b0ecea12f7.png)

Another proposal is to also add a visual indicator for the mode:

![image](https://user-images.githubusercontent.com/4534299/93592877-4462a880-f9b3-11ea-93d7-b7b09ea89f0a.png)

![image](https://user-images.githubusercontent.com/4534299/93592893-4c224d00-f9b3-11ea-9a90-18f92395085c.png)

For `Charger only` it can be orange. 

Alternatively, we can change the main icon of the widget if you consider that the text in the subtitle is not enough.

@martinbosma, what do you think?

**Comment by martinbosma** [comment]
@AlexImb I would say the text is enough, as the colors don't add extra info. 

>Alternatively, we can change the main icon of the widget if you consider that the text in the subtitle is not enough.

How would you propose to change it? Change the color or design icons for on/off/charger only?

Just for clarification: this change is only when the mode is not adjustable, i.e. when a VE.Bus BMS is present in the system, right?
And not when the ui is locked as per #105

**Comment by AlexImb** [comment]
> How would you propose to change it? Change the color or design icons for on/off/charger only?

Yes, have different icons for the modes on the same white background.

> Just for clarification: this change is only when the mode is not adjustable, i.e. when a VE.Bus BMS is present in the system, right?
> And not when the ui is locked as per #105

Yes, when the UI is locked the buttons are just disabled. This is only when `/ModeIsAdjustable` is 0.

**Comment by martinbosma** [comment]
>>How would you propose to change it? Change the color or design icons for on/off/charger only?
>
> Yes, have different icons for the modes on the same white background.

I think showing the text is sufficient. I don't think changing the icon has added value as the user doesn't know he can also look at the icon.

>>Just for clarification: this change is only when the mode is not adjustable, i.e. when a VE.Bus BMS is present in the system, right?
>>And not when the ui is locked as per #105
>
>Yes, when the UI is locked the buttons are just disabled. This is only when /ModeIsAdjustable is 0.

Ok, clear. I was a bit concerned about the height of the widget changing dynamically and then the widgets are rearranging and jumping all over the place. However, `/ModeIsAdjustable` does not change unless you change the system/hardware.

**Comment by AlexImb** [comment]
Ok, then we go for the text only. 

This is how it looks for simulation (m) from `venus-docker`: 

![image](https://user-images.githubusercontent.com/4534299/93600652-42531680-f9c0-11ea-824f-9d19ca2a9fb5.png)

**Comment by martinbosma** [comment]
lgtm
