### ISSUE TITLE
Enable MQTT instructions are outdated

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#118]
The screenshot and instructions shown when a MQTT connection cannot be made are outdated.

The following is shown:
![image](https://user-images.githubusercontent.com/6614648/71890227-1ea6b380-3144-11ea-8069-aa81a20de853.png)

But the current services page on a GX device looks like this (v2.42):
![image](https://user-images.githubusercontent.com/6614648/71890426-8a891c00-3144-11ea-8cc2-1ddd96fdea86.png)

Both `MQTT on LAN (SSL)` and `MQTT on LAN (Plaintext)` must be enabled.

**Comment by AlexImb** [comment]
On CCGX v2.42 in Demo mode looks like this:

![image](https://user-images.githubusercontent.com/4534299/71905174-e6b16780-3167-11ea-9f4d-077e82273bcf.png)

I updated the instructions with that picture and rounded the borders:

![image](https://user-images.githubusercontent.com/4534299/71905919-61c74d80-3169-11ea-8147-393e2f811ac5.png)

I can also update the text if you think it's necessary.

**Comment by martinbosma** [comment]
Where is the access level set to? If it's set to `Service` or `Superuser` then it shows `NMEA2000 on MQTT` in the Services menu. This is not available when the access level is set to `User` or `User & Installer`, which is the most common use case.

**Comment by martinbosma** [comment]
And can you change the text that `Remote Control > Settings > Services > MQTT on LAN (Plaintext)` must be enabled? Instead of just `MQTT`.

**Comment by AlexImb** [comment]
It was set to `Superuser` indeed. Set it to `User & Installer` and now it looks like this:

![image](https://user-images.githubusercontent.com/4534299/71907749-f2535d00-316c-11ea-89af-516e1180574f.png)

**Comment by martinbosma** [comment]
Perfect!
