### ISSUE TITLE
Remote console conditionally display topic path

### ISSUE THREAD

**Issue by AlexImb** [victronenergy/venus-html5-app#120]
I found the following TODO in the code and I was wondering if this is already implemented so I can use the right path.

```
// TODO Add topic for SystemSetup and then change value passed to header
showRemoteConsoleSetting: `N/${portalId}/settings/0/Settings/SystemSetup/<placeholder>`
```

Perhaps one or a combination of these:
![image](https://user-images.githubusercontent.com/4534299/71902317-18bfcb00-3162-11ea-9c9a-158b13b731ed.png)

**Comment by martinbosma** [comment]
You mean [this](https://github.com/victronenergy/venus-html5-app/blob/7c18c630b35efd1dc556226c44570a8fdeaa54af/src/app/components/Header/Header.js#L30), right?

I can't remember what the idea was behind this. It's to show/hide the remote console button based on the value of the property? 

Right know [it's always visible](https://github.com/victronenergy/venus-html5-app/blob/7c18c630b35efd1dc556226c44570a8fdeaa54af/src/app/components/Header/Header.js#L42), regardless of the value of the property?

**Comment by martinbosma** [comment]
The correct topic is: `N/${portalId}/settings/0/Settings/System/VncLocal`

**Comment by AlexImb** [comment]
Yes, that's what I meant. I'll use that topic. Thank you!
