### ISSUE TITLE
For certain aspect ratios the MQTT instructions are out of the viewport

### ISSUE THREAD

**Issue by AlexImb** [victronenergy/venus-html5-app#128]
![image](https://user-images.githubusercontent.com/4534299/73768829-fda0a500-4779-11ea-8d0b-9d4ae5cd1d4e.png)

A solution for this will be to show two columns (instructions on the left and VNC image on the right) for wide aspect ratios with a low height.

**Comment by martinbosma** [comment]
Can you make a mockup of the two column option to see how it looks? 

And what happens with screens with a "normal" aspect ratio, but low resolution? Is the text and image then simply scaled down?

**Comment by AlexImb** [comment]
> And what happens with screens with a "normal" aspect ratio, but low resolution? Is the text and image then simply scaled down?

It was not scaling down. Not it does. Combined with the 2-column view for low height it looks like this:

![image](https://user-images.githubusercontent.com/4534299/74649041-18faaf80-517f-11ea-9973-532910c88fb0.png)

![image](https://user-images.githubusercontent.com/4534299/74649076-2b74e900-517f-11ea-92bd-abb4d9ac39c8.png)

![image](https://user-images.githubusercontent.com/4534299/74649113-3fb8e600-517f-11ea-99d3-706acbfe391d.png)
