### ISSUE TITLE
Add paginated views

### ISSUE THREAD

**Issue by AlexImb** [victronenergy/venus-html5-app#138]
The current implementation hides the metrics that are not inside in the viewport. Due to the increasing number of metrics/widgets this might be a problem for some complex installations. 

A solution for this will be to add pages and controls (and gestures) to navigate trough them.

@martinbosma What do you think?

**Comment by AlexImb** [comment]
![image](https://user-images.githubusercontent.com/4534299/86023159-98e92e00-ba2b-11ea-95de-e5b3a0adf1a0.png)

This is how it looks until now. Still to implement:

- [ ] swipe gestures for switching between the pages

**Comment by mpvader** [comment]
Hi, I haven't checked what data then gets pushed to a second page - but take care that a lot of effort went into the original design to get all information one page.

**Comment by johanneshovda** [comment]
You could consider pagination within each component/section, instead of the entire page. 
That way, you can see e.g the battery section, which would then paginate to show more than X number of batteries. 

I would suggest the importance of seeing all components on one page, rather than not be aware of status on a secondary page you might not realize existed..

**Comment by AlexImb** [comment]
The pagination is active only when the components don't fit on the screen after reducing their height trough other means such as reducing the margins and paginating the battery list. The screens that already show all the metrics on one page won't be affected. The current implementation, as well as the previous ones, hide the components without any way of seeing or knowing that they are being hidden. 

On small and split screens only the first 2-3 components are currently displayed:

![image](https://user-images.githubusercontent.com/4534299/86238384-b2aa8280-bb9d-11ea-9071-8bd9dff4c40f.png)

By adding pagination, all the components can be displayed on those small screens as well: 

![image](https://user-images.githubusercontent.com/4534299/86238732-4ed48980-bb9e-11ea-93b8-1ff2bebd8beb.png)

![image](https://user-images.githubusercontent.com/4534299/86239926-7d536400-bba0-11ea-8e80-58055658dbea.png)

The pagination of individual components as used in the Batteries component is not really applicable for the other components. Maybe the ones that are displaying information for all 3 phases can make use of that:

![image](https://user-images.githubusercontent.com/4534299/86239236-39ac2a80-bb9f-11ea-884c-d3afc3a367cb.png)

Having paginated screens and arrows to navigate trough them seems to be the pattern also used by the native apps running on the MFDs: 

![image](https://user-images.githubusercontent.com/4534299/86240164-f2bf3480-bba0-11ea-8221-b1216d64d15d.png)

@mpvader @johanneshovda @martinbosma What do you think? Should I continue with finishing the screens pagination or look into alternative solutions?

**Comment by martinbosma** [comment]
@AlexImb I think this already looks is nice and is much better then just hiding widgets without any indication. I'm fine with proceeding working on this solution.

What would be the alternative solution(s) then?

**Comment by AlexImb** [comment]
> What would be the alternative solution(s) then?

To find a way to fit all the information on the screen at any size, which might involve hiding icons, reducing margins/padding, etc. However, I think that pagination is a better solution long-term because new metric components will probably be added later on.

**Comment by martinbosma** [comment]
I agree
