### ISSUE TITLE
App update in Venus GX hardware

### ISSUE THREAD

**Issue by marcoemanuelecocco** [victronenergy/venus-html5-app#141]
in the victron venus GX how can I update the app, since I only find a www / app folder with a very small part of the interface?

**Comment by martinbosma** [comment]
Hi @marcoemanuelecocco, the HTML5 app is shipped with VenusOS and will be automatically updated once we decide to include a new version. The next update for the HTML5 app is scheduled for Venus v2.60.

If you manually want to update the app, I would recommend to follow [these ](https://github.com/victronenergy/venus-html5-app/blob/master/README.md)instructions. Note that a manually uploaded version will be overwritten with the version from Venus in case of a firmware update.

**Comment by marcoemanuelecocco** [comment]
I've installed the 2.6.30 but don't see the update about pagination...

Il Ven 10 Lug 2020, 08:25 Martin Bosma <notifications@github.com> ha
scritto:

**Comment by martinbosma** [comment]
The screen pagination is not included in Venus yet, at it is still work in progress.
