### ISSUE TITLE
Combine the Generator control component with the ActiveSource

### ISSUE THREAD

**Issue by AlexImb** [victronenergy/venus-html5-app#142]
At the moment, the component that controls the generator using the internal relay of a GX device (Generator) is separate from the one that displays the measurements from the connected AC Inputs (ActiveSource).

![image](https://user-images.githubusercontent.com/4534299/88641801-f79fd700-d0bf-11ea-950b-9d4d615990f1.png)

**Comment by AlexImb** [comment]
The combined Generator control and AC Input (ActiveSource) is implemented and has the following states:

AC Input 1: Generator
Relay Function: not Generator Start/stop

![image](https://user-images.githubusercontent.com/4534299/88899643-978b6b00-d24e-11ea-901c-7f1bf08fe255.png)

AC Input 1: Generator
Relay Function: Generator Start/stop

![image](https://user-images.githubusercontent.com/4534299/88899790-c99ccd00-d24e-11ea-8a3c-cd0983906688.png)

AC Input 1: Not available
AC Input 2:  Not available
Relay Function: Generator Start/stop

![image](https://user-images.githubusercontent.com/4534299/88900397-9d358080-d24f-11ea-9334-fee38c003e59.png)

AC Input 1: Generator
AC Input 2: Generator
Relay Function: Generator Start/stop

Note: The buttons from both metrics control the same Generator (`/0/Generator0`) because it is not possible to know which generator is connected to which AC Input.

![image](https://user-images.githubusercontent.com/4534299/88899981-0963b480-d24f-11ea-9aef-42f405252d0b.png)

With data:

Simulation L: Quattro + BMV - boat with generator - three phase

![image](https://user-images.githubusercontent.com/4534299/88900802-395f8780-d250-11ea-9cd6-fce7e5c387e3.png)

Simulation F: Quattro + BMV - boat with generator - single phase

![image](https://user-images.githubusercontent.com/4534299/88901043-90fdf300-d250-11ea-8403-98f0a1675ea0.png)

The Fisher Panda Genset is still a separate component so the following case in which another Generator is connected to the AC Input is theoretically still possible: 

![image](https://user-images.githubusercontent.com/4534299/88901368-feaa1f00-d250-11ea-9163-f77200901561.png)

If the FP Genset will be the one connected to the AC Input then the measurements will be displayed in both components. However, they will come from different sources: `/genset/0/Ac/*` for the FP Genset and `/vebus/${vebusInstanceId}/Ac/*` for the Generator one. 

Hiding Generator component(s) when the FP Genset component is present is an option, but considering that it is not possible to know to which AC Input is connected or if it is connected at all (as far as I know) I would suggest to keep both. 

@martinbosma What do you think?

**Comment by martinbosma** [comment]
@AlexImb Looks good!

>Hiding Generator component(s) when the FP Genset component is present is an option, but considering that it is not possible to know to which AC Input is connected or if it is connected at all (as far as I know) I would suggest to keep both.

Yes, keep both. In theory there can be loads connected directly to the generator, which will not be visible on the AcSource widget.

**Comment by AlexImb** [comment]
Closed via #143
