### ISSUE TITLE
AC Loads/In: Hide 3rd phase in case of 2-phase system

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#149]
The `AcLoads` & `ActiveSource` widgets show invalid values for the 3rd phase in case of a 2-phase system.

**Fix**
Show as many phases as reported by `N/${portalId}/system/0/Ac/Consumption/NumberOfPhases`
See [AcLoads](https://github.com/victronenergy/venus-html5-app/blob/master/src/app/components/AcLoads/AcLoads.js#L35) & [ActiveSource](https://github.com/victronenergy/venus-html5-app/blob/master/src/app/components/ActiveSource/ActiveSource.js#L53).

![image](https://user-images.githubusercontent.com/6614648/91439491-572f0500-e86d-11ea-875a-7eaab1f9e04a.png)

See [original post](https://community.victronenergy.com/questions/60074/venus-os-v26041-available-for-testing.html?childToView=60070#answer-60070) on community.

**Comment by AlexImb** [comment]
@martinbosma I made a fix for this in #150. 

ActiveSource and GeneratorRelay use: `N/${portalId}/vebus/${vebusInstanceId}/Ac/NumberOfPhases`
AcLoads uses: `N/${portalId}/system/0/Ac/Consumption/NumberOfPhases`
GeneratorFp uses: `N/${portalId}/genset/0/NrOfPhases`

**Comment by martinbosma** [comment]
Ok, unfortunately we don't have a 2-phase system to test on. Perhaps we (or you) can make a simulation in the docker image.
Or perhaps you have some test scripts and were already able to test this.

**Comment by AlexImb** [comment]
I added some unit tests that simulate 1, 2, and 3 phase systems for AcLoads. Looks like this:

![image](https://user-images.githubusercontent.com/4534299/93769018-935e4700-fc1a-11ea-8a92-3ed03f1a13d8.png)

![image](https://user-images.githubusercontent.com/4534299/93768974-817ca400-fc1a-11ea-84e9-e34bd39c006b.png)

![image](https://user-images.githubusercontent.com/4534299/93769067-9eb17280-fc1a-11ea-91ad-cce05902132c.png)
