### ISSUE TITLE
Tanks not shown

### ISSUE THREAD

**Issue by buijsp** [victronenergy/venus-html5-app#174]
Devices not shown are:
Tanks: they'll be already shown else where on a Marine MFD; mostly in the native MFD UI.

Since there is a GX Tank140 that is not always true!

**Comment by mpvader** [comment]
Hi, well, if you enable the NMEA2000-out function; (and make for a NME2000 connection between the GX and your MFD) then you can see those as well natively on the MFD.

**Comment by buijsp** [comment]
That is true but needs to configure NMEA2000 (CAN) aswell, and extra cables and settings on both sides GX and MFD.

**Comment by mpvader** [comment]
There will be tanks in the future; its under design

**Comment by mpvader** [comment]
Hey Peter, don’t worry: tanks are still coming - also with this issue closed; goed weekend
