### ISSUE TITLE
AC charger shows wrong fault state

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#178]
This (non-VE.Bus) charger shows `VE.Bus fault condition` state, while this should just be `Fault`.
![image](https://user-images.githubusercontent.com/6614648/135080375-4d460393-f931-44b5-85d2-1a564e6d2aa7.png)

**Comment by martinbosma** [comment]
It seems that same decription was used for VE.Bus and non-VE.Bus products:
https://github.com/victronenergy/venus-html5-app/blob/1ac805811241cce6e69e553f0c85d3b155c8cf6e/src/app/utils/util.js#L57
https://github.com/victronenergy/venus-html5-app/blob/012b0309d0993482d7e7ebece279050962cdce3e/src/app/locales/languages/nl.json#L59

Perhaps this can simply be refactored to `"veBusFault": "Fault",` or `"fault": "Fault", `

**Comment by ni3k** [comment]
implemented the suggestion
