### ISSUE TITLE
Add Tank display option

### ISSUE THREAD

**Issue by johanneshovda** [victronenergy/venus-html5-app#180]
I'm looking at this from the context of a motorhome, where I have a single display for all controls and indicators, driven by the Venus app.
The one major thing missing is the Tank display. 
The tanks are already connected to the Venus, and show up in the Venus remote console, but I much prefer to use the HTML5 app, since it looks so much sleeker and cleaner.

I can understand a marine scenario with tank senders already connected to other gauges, but in an OEM/Mobile Home scenario it would make sense to have the option to show the tank information as well.
![BP11814](https://user-images.githubusercontent.com/65792874/136382006-0f0d3b53-5ab1-46bd-820b-6e42729aaf5d.jpeg)

**Comment by mikael-floden** [comment]
Have there been any progress on this? I'm looking for the exakt same feature. This allows our van to have a single nice looking display that includes water tank level, LPG tank level, etc.

I get goosebumps by just thinking about it!

**Comment by AlexImb** [comment]
There is new, redesigned version of this app, soon to be released. That includes tanks and tank types.
