### ISSUE TITLE
Icon not visible in browser tab

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#181]
Just a minor issue, but the white icon is not visible when the tab is active; it is (barely) when the tab is not active.
Observed with chrome and html5-app version 2.0.8 Marine.
![image](https://user-images.githubusercontent.com/6614648/136402439-87ae9626-73df-4993-b61b-6329dc1b73eb.png)

**Comment by JoshuaDodds** [comment]
Please see PR #200 and test if this branch fixes your issue.  Thanks!
