### ISSUE TITLE
BMV-712 Battery Temperature

### ISSUE THREAD

**Issue by gharshaw** [victronenergy/venus-html5-app#182]
Is it posible to add the BMV-712 Battery Temperature to the HTML5 app?

**Comment by JoshuaDodds** [comment]
I believe my PR found here: https://github.com/victronenergy/venus-html5-app/pull/200  should add this functionality for you.  Can you checkout my branch and test for me ? Post a screenshot of your results, please 👍

**Comment by martinbosma** [comment]
This was added in v3.x.x
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/14ec9583-577f-44d6-988e-de79fe160225)
