### ISSUE TITLE
Remote console small on high resolution displays

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#192]
Got a complaint from a customer and also confirmed on a Garmin 8412 that remote console is quite small.
The regular widgets do scale fine, but for the remote console there is some room for improvement.

Screenshot of Garmin 8412; it's a bit hard to see the actual size of the remote console here.
![3366170214_05JUN21_0625_00](https://user-images.githubusercontent.com/6614648/166643152-65967ce6-9337-417e-854d-93f35dd28197.png)

Below a few screenshots to compare different screen sizes. 
The absolute size obviously also depends on the physical size of the screen, so remote console will be much smaller on a 12" screen (Garmin 8412) than on a 24" screen (Garmin 8424) with the same resolution.

Screenshot 1920x1280, similar to Garmin 8412 (12")
![image](https://user-images.githubusercontent.com/6614648/166650741-d99d4708-3d45-4adb-9fb2-143f4f96b6eb.png)

Screenshot 1280x800, similar to Garmin A12 (12")
![image](https://user-images.githubusercontent.com/6614648/166650620-5b2e5be1-f8c2-4b77-8f21-76e3c8437994.png)

**Comment by JoshuaDodds** [comment]
Hi there, 

Could you checkout this fork and see if it fixes the issue for you?

https://github.com/victronenergy/venus-html5-app/pull/200

Let me know if i can help with anything!

**Comment by octafishmedia** [comment]
I have this issue on a 9" Garmin screen. Is there a solution released? A "200%" or "max-width" button would be great.

**Comment by martinbosma** [comment]
This was fixed in v3.x.x somewhere

**Comment by octafishmedia** [comment]
It was indeed - v. 2.30! Now we’re talking.
