### ISSUE TITLE
"Your dashboard is empty" shown briefly when devices are present

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#193]
As you can see on the video, the dashboard empty page is briefly shown when the HTML5 app is opened even though there are devices present.  Is this something that can be improved?

Also loading of the page/widgets is quite slow, but I don't know if this is related to the MFD itself or the GX device.

The video was taken on a Garmin 8412 with a Cerbo  GX.
https://user-images.githubusercontent.com/6614648/166653920-40004b1d-bd77-4018-bb62-67b429e90d0c.mp4

**Comment by mpvader** [comment]
this is about the old version - no longer relevant
