### ISSUE TITLE
Add support for DC generators

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#195]
See https://github.com/victronenergy/venus-private/issues/162 and https://github.com/victronenergy/venus-private/issues/232

New items added for DC generators (compared to AC gensets), see also [dbus wiki](https://github.com/victronenergy/venus/wiki/dbus#generator-data):
```
com.victronenergy.dcgenset is used for DC gensets.

/Dc/0/Voltage        -> DC output voltage
/Dc/0/current        -> DC output current
/Dc/0/Power          -> DC output power
/HeatsinkTemperature -> Temperature of the heatsink
```

The design of DC genset can be similar to the AC genset, except show DC data instead of AC data.

Mockup:
![image](https://github.com/user-attachments/assets/7feae4a7-07f9-4a88-a0f3-d5b2c7993e6f)
![image](https://github.com/user-attachments/assets/65a22230-ac83-4405-ab87-d92a8f03fd0d)
1) Show DC data instead of AC data
2) Add heatsink temperature (if present)

MQTT data
![image](https://github.com/user-attachments/assets/24e3aa9d-aa59-43dd-b921-acbbbc8bc682)

**Comment by mman** [comment]
Addressed by https://github.com/victronenergy/venus-html5-app/commit/c85fea121ea009d171053de90cbf72d9c7ff7c5a, except for `/HeatsinkTemperature -> Temperature of the heatsink`
