### ISSUE TITLE
Multiplus inverter switching broken on 2.90~14 Large

### ISSUE THREAD

**Issue by zorrobyte** [victronenergy/venus-html5-app#197]
When running the large image which includes the "Inverter Only" menu option, my Multiplus will not turn back on after being turned off from the Web UI.

<img width="338" alt="Screen Shot 2022-07-17 at 5 48 45 PM" src="https://user-images.githubusercontent.com/7257172/179426145-67a3ede6-c655-43fd-a8c5-791ceffced97.png">

I have to unplug the ethernet cable (ve bus) for it to switch back on and abstain from using the UI, touchscreen, or VRM to switch modes.

Rolling back to a stable release works normally. 

The multiplus and all attached hardware is running the latest versions available.

**Comment by JoshuaDodds** [comment]
I think you opened an issue in the wrong repo.  That screenshot does not look like its from the venus-html5-app.
