### ISSUE TITLE
wont run in latest lts version of node.js 

### ISSUE THREAD

**Issue by eaglenest-zz** [victronenergy/venus-html5-app#205]
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

**Comment by eaglenest-zz** [comment]
i just installed node 16 version but soon will not be an option

**Comment by Lippur** [comment]
We're working on upgrading the app dependencies, incl. support for the latest LTS runtime.

**Comment by AlexImb** [comment]
A solution for this issue is implemented in the `marine2` branch.
