### ISSUE TITLE
Add Solar panel part?

### ISSUE THREAD

**Issue by LeeNX** [victronenergy/venus-html5-app#21]
Like to thank the people working on this fine piece of code, really lets me drop a tablet or something in our house to show off VictronEnery details without internet access.  
  
I am no developer, so I can't really help with the app, other than ask for nice features and possible give some feedback. Can we get Solar panel input monitoring vs the shoreline data?  
  
Also hoping this is the right place to put in feature requests and bug reports? Don't remember seeing any place in the repo ReadMe, but that has changed a bit since I first looked at this month ago.  
  
Either way, this is awesome work, thanks!

**Comment by mpvader** [comment]
Hey @LeeNX; my apologies for the slow reply! I was not monitoring this issue list.

Yes; we'll also add monitoring solar. Its on the list.

**Comment by mpvader** [comment]
The issue to monitor is this one: #52.


Closing this one as a duplicate.

**Comment by LeeNX** [comment]
@mpvader - No worries, thanks for the great work and feedback!
