### ISSUE TITLE
can't be build on a Raspberry Pi

### ISSUE THREAD

**Issue by Head** [victronenergy/venus-html5-app#217]
I've tried to build https://github.com/victronenergy/venus-docker on a Raspberry Pi and ended up here.
The build process failes at Cypress, which is not available for the Raspberry.
Also with `npm install --omit=dev` the process failes.

**Comment by AlexImb** [comment]
Hello,

We do not support building for Raspberry Pi (arm-architecture). Venus-docker is designed only for development of UIs locally and simulating data. 

If you need to run Venus on a Raspberry Pi please refer to this repo: https://github.com/victronenergy/venus and the Victron Community.

I hope this helps!
