### ISSUE TITLE
Problem with Manifest on iOS

### ISSUE THREAD

**Issue by freakent** [victronenergy/venus-html5-app#290]
In Safari on iOS you can open a ~WPA~ PWA then install it by doing a "Add to Home Screen". Your manifest file is served from the url <host>/app/Marine/ so iOS assumes this is the path to the app. iOS does not let you change this. When you tap the icon the app gives a 404 error as it can not find a resource at /app/Marine. The spec says manifest files should be served from the root of your application, which would be /app. You should change the path to the manifest inside the html head or update routing so the home page is also available at /app/Marine.

**Comment by AlexImb** [comment]
Hi @freakent,

We are going to check this. 

Thank you for reporting.

**Comment by frankwaalkens** [comment]
Implemented in Release 3.1.2-beta Marine2
