### ISSUE TITLE
Possible issue with caching

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus-html5-app#314]
There have been a few reports that browsers do not automatically load the new application. What those users are seeing then is the prior version, from before the redesign.

This one:
![image](https://github.com/victronenergy/venus-html5-app/assets/5200296/cb43d592-301b-4d21-bd6d-f2d286b9879b)
https://community.victronenergy.com/questions/216297/venus-os-v31011-available-for-testing.html?childToView=222520#comment-222520

And also one by Wiebe in Slack:
https://victrondevelopment.slack.com/archives/CDBK9A71S/p1685948767711909

**Comment by wiebeytec** [comment]
The patch for Venus has been prepared to put `add_header Cache-Control "no-cache";` in the Nginx config file. Contrary to how that reads, browsers still store a cached copy, but it will always be re-validated.
