### ISSUE TITLE
As a user, I don't want to see the input current limit in my device list

### ISSUE THREAD

**Issue by AlexImb** [victronenergy/venus-html5-app#322]
![image](https://github.com/victronenergy/venus-html5-app/assets/4534299/7e4cf56b-c413-468c-b6bc-248358e8917a)

Status: Ongoing discussion. It's implemented as per design but might need to change

Internal discussion: https://victrondevelopment.slack.com/archives/CDBK9A71S/p1682142496123079

**Comment by martinbosma** [comment]
Another report from Community:
https://community.victronenergy.com/questions/231599/venus-os-v3202-available-for-testing.html

>Under Devices, not sure what the line "Bulk charging" is. If this is the Multi's charger output (to battery, it should be labeled as such. But this is not consistent with what's happening in my system at the time of the screen shot as the Multi is charging the battery at about 900 watts.
![61435-screenshot-2023-09-17-at-84033-am](https://github.com/victronenergy/venus-html5-app/assets/6614648/44fd83c0-54d1-4dd8-971f-046ce9340752)

**Comment by mpvader** [comment]
Ok
