### ISSUE TITLE
Generator power unit does not correspond with value

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#327]
In system overview it the unit kW, but the value is in watts; should be 3.7kW.
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/f37fc1f3-c336-4d3a-82e6-0d07f1656d4b)

In the detailed view the unit is W for L2 and L3, but the value is kW. L1 is correct in this case, but should also be shown in kW.
The values should be 0.9kW, 1.5kW, 1.4kW, to have a nice alignment. When one value > 1000W => show them all as kW.
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/98a4d752-9870-438b-a8fd-c25dd249da0c)

It should be like the power readings in below picture (taken from the design file).
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/78f56a22-7ed2-4cc9-830f-cd7c609eb1ef)

**Comment by fwaalkens** [comment]
@martinbosma Collective phase unit formatting to seperate issue if thats possible.
