### ISSUE TITLE
I want to see Watts instead of Amps

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#336]
From Community:
https://community.victronenergy.com/questions/231599/venus-os-v3202-available-for-testing.html

>
![61425-screenshot-2023-09-17-at-82656-am](https://github.com/victronenergy/venus-html5-app/assets/6614648/7afe4d04-adff-4ea8-be25-f52119a7ca28)
I can't find a way to select power as apposed to current. I realize that many want to see current but power is more constant across multiple subsystems (AC in/out and battery or PV charger.

During the design state this topic has also been addressed, but no action taken yet.
We could provide an option to toggle between amps and watts in the views.

**Comment by mpvader** [comment]
pls check with @jepefe  and Serj on how we're handling this in guiv2.

**Comment by mr-manuel** [comment]
Any updates on this? I would also like to see watts instead of amps.

**Comment by martinbosma** [comment]
Hi @mr-manuel, no update I'm afraid. We are working towards a performance upgrade, including some minor bug fixes and improvements. This is not part of it.

**Comment by martinbosma** [comment]
I'd opt to rely on the same setting as gui-v2 as mr-manuel is suggesting, which is `/Settings/Gui/ElectricalPowerIndicator`, where 0=Watts and 1=Amps. However, in gui-v2 that setting seems to be broken, as it is not accepting Amps as value in the settings menu.

**Comment by mman** [comment]
I'll try to infer the behaviour from settings... that will make things super simple :)

**Comment by mman** [comment]
Step 1. complete here: https://github.com/victronenergy/victron-mfd-modules/commit/f140d0bfee60430fc3f523d501a2ce8ea219e866

**Comment by mman** [comment]
Step 2. available via https://github.com/victronenergy/venus-html5-app/pull/437

<img width="1222" alt="Screenshot 2024-09-27 at 15 47 14" src="https://github.com/user-attachments/assets/e26ed9e3-4d6b-4754-a05b-a535b569c36c">


<img width="1222" alt="Screenshot 2024-09-27 at 15 47 03" src="https://github.com/user-attachments/assets/93a11e71-6d79-4775-ba5f-2c289270b2cc">
