### ISSUE TITLE
Fix vulnerabilities 

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#348]
Check for vulnerabilities in packages and update accordingly. 
There are still a few dependabot branches here which need checking and I've got some security advisories from GH. 
Make sure the packages don't break functionality.

**Comment by frankwaalkens** [comment]
- Updated decprecated svg related packages
- Removed old Storybook and related files
- Upgraded @babel/core
- Upgraded tailwind, removed line-clamp package (included by default in 3.3.0).
