### ISSUE TITLE
Ukrainian translations not working

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#350]
Recently Ukrainian translations were added, but when selecting the language it does not apply it on the app.
To enable Ukrainian language go to Remote Console, Settings -> Display & language -> Language and select Yкраїнська.
Selecting any other language will apply its translations immediately.

![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/d13f214c-4a6c-4a07-a57a-7371e2ebf022)

**Comment by fwaalkens** [comment]
Added missing translation key to constants: https://github.com/victronenergy/venus-html5-app/commit/76ba9b092528e15a4ffbbe49b917e8631b53848c
