### ISSUE TITLE
tank values/gauges not aligned properly

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#356]
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/40dc1879-2134-4ea0-9707-7e99778a08f7)
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/e5e82a42-3830-4d85-b15e-af2acdbe91ff)

**Comment by martinbosma** [comment]
Some more minor (related) things:
![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/c8a88845-7475-4348-bb35-5cd01a887768)

1. Mismatching icon size, also causing misalignment on text.
2. Right hand side margin not respected.

**Comment by fwaalkens** [comment]
Solved in https://github.com/victronenergy/venus-html5-app/pull/363
