### ISSUE TITLE
battery gauge not properly drawn

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#358]
Seems like the battery gauge is too small, lots of empty space around it.
The text does seem to have the proper size.

![image](https://github.com/victronenergy/venus-html5-app/assets/6614648/517bda20-7dda-4b89-8540-f7f69fc3c87f)

View port size: 1690x500

**Comment by fwaalkens** [comment]
Resolved in commit a740eaca5f959d734d8ec6cdde66a0e9227eb272
