### ISSUE TITLE
generator: rename /AutoStart path

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#381]
https://github.com/victronenergy/venus/issues/1267

**Comment by mman** [comment]
Currently the generator auto start code seems to live here: https://github.com/search?q=repo%3Avictronenergy%2Fvictron-mfd-modules%20%22%2FAutoStart%22&type=code

For Fisher Panda:

https://github.com/victronenergy/victron-mfd-modules/blob/f6e1fb434fb821486ed663c4a27011f7f46ec469/src/Modules/Generators/GeneratorFp.provider.ts#L34-L38

For Relay based generator:

https://github.com/victronenergy/victron-mfd-modules/blob/f6e1fb434fb821486ed663c4a27011f7f46ec469/src/Modules/Generators/GeneratorRelay.provider.ts#L37-L55
