### ISSUE TITLE
Add pending state for Lynx Smart BMS

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#391]
For the redundancy feature, a new state has been added to the Lynx Smart BMS: pending. This means that it is waiting to close its contactor. In order display this state, it first must be added to the list of batteries, available on `N/<vrm id>/system/0/Batteries`.

The pending state needs to be shown if `bmstate === 18`, else the existing logic can be used.

The idea is to show the pending state in place op the current state. Here is a simple mock-up, not considering actual data (when a BMS is in the pending state, its contactor is open and likely does not have any other measurements).
![image](https://github.com/user-attachments/assets/4b60ee23-6cef-4fee-a649-e4cbbbd28e38)
![image](https://github.com/user-attachments/assets/4589e30c-64f0-4bd7-9ec9-7d66b79b0a4e)

**Comment by martinbosma** [comment]
@mman This has been added to [systemcalc](https://github.com/victronenergy/dbus-systemcalc-py/commit/c26994f7b366bad17a1b2a89dc521780fa57498b). You should be able to use the venus-docker to simulate this.

**Comment by mman** [comment]
@martinbosma Which `Venus-docker` simulation do you suggest to use? The `lp` one we added couple months back is broken and does not property display the Lynx BMS instances...

**Comment by martinbosma** [comment]
The `lp` simulation should be the one. I will have a look why it is broken and try to fix it.

**Comment by mman** [comment]
Thanks @martinbosma, please ping me when you think is ready... I will re-test
