### ISSUE TITLE
Different size battery gauge

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#406]
In below screenshot the first battery gauge is bigger than the others, while the second one contains the same data, except for the name,
![image](https://github.com/user-attachments/assets/21e644a9-8803-41d5-a665-0a60f4163385)

**Comment by mman** [comment]
@martinbosma What simulation is that please and what OS/browser did you use to trigger it?

**Comment by martinbosma** [comment]
It's the `bct` simulation and I'm using Firefox.
![image](https://github.com/user-attachments/assets/07441d81-9a4e-4a12-a3ed-326cde8b9e31)

**Comment by mman** [comment]
Got it, happens only after the battery widget reaches certain size, but I can reproduce it in Safari as well as in Firefox.


https://github.com/user-attachments/assets/e9a19922-0931-4020-96d2-f1068439caab

The bigger green circle is 700pt at its maximum while the smaller ones are at 600pt when they break.

<img width="972" alt="Screenshot 2024-09-11 at 14 55 25" src="https://github.com/user-attachments/assets/61411af6-808b-490a-844c-15327328c689">

Looks like the flex layout is getting confused by the labels where first one captures more space and therefore determines what would be the size of the circle. /me going to learn about the flex box thingy.
