### ISSUE TITLE
no battery data shown if watts is selected but power is not available

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#453]
For example simulation `gdh`:

With watts:
![image](https://github.com/user-attachments/assets/ef2edf28-2954-405b-8d07-0f63f9593220)

With amps:
![image](https://github.com/user-attachments/assets/2b78e70c-2fd6-41d6-907f-6df999e50018)

Perhaps always keep voltage, but toggle amps/watts.
Same applies for a more advanced battery with soc, as I think voltage does have added value.
![image](https://github.com/user-attachments/assets/bdf3c379-d76b-4e96-8327-f2fb4968cd4c)
![image](https://github.com/user-attachments/assets/ffb3094d-cd01-4818-8b78-6edb881daa2b)

**Comment by mman** [comment]
Fixed by https://github.com/victronenergy/venus-html5-app/commit/7b8e186dfae9a6662db29dfabbae192eae3349c5
