### ISSUE TITLE
Show Solar charger info

### ISSUE THREAD

**Issue by ucorina** [victronenergy/venus-html5-app#52]
Solar-charger: box that is present when there are one or more Solar-charger installed. Data is already available from System-calc: the total power coming from solar. Data to be shown is output power (/Dc/Pv/Power), and the output current (/Dc/Pv/Current).

**Comment by thomhos** [comment]
Implemented, needs testing and code review.

**Comment by ucorina** [comment]
Implementation done. Box is shown when `/Dc/Pv/Power` and `/Dc/Pv/Current` are not empty.

<img width="530" alt="screenshot 2019-01-07 14 47 47" src="https://user-images.githubusercontent.com/1322468/50771647-80131880-128b-11e9-96c0-5b5e22eec653.png">
