### ISSUE TITLE
Support for 3 phase AC systems

### ISSUE THREAD

**Issue by ucorina** [victronenergy/venus-html5-app#80]
Regarding 3 phase systems: there will be three AC voltages; and three AC currents, and also three AC powers for the `AC Loads` box. And same for Generator and Shore power boxes.

**Topics for AC Loads:**

Check number of phases:
`N/${portalId}/system/0/Ac/ConsumptionOnOutput/NumberOfPhases`
Current:
`N/${portalId}/vebus/${vebusInstanceId}/Ac/Out/L1/I`,
`N/${portalId}/vebus/${vebusInstanceId}/Ac/Out/L2/I`,
`N/${portalId}/vebus/${vebusInstanceId}/Ac/Out/L3/I`
Voltage:
`N/${portalId}/vebus/${vebusInstanceId}/Ac/Out/L1/V`,
`N/${portalId}/vebus/${vebusInstanceId}/Ac/Out/L2/V`,
`N/${portalId}/vebus/${vebusInstanceId}/Ac/Out/L3/V`
Power:
`N/${portalId}/system/0/Ac/ConsumptionOnOutput/L1/Power`
`N/${portalId}/system/0/Ac/ConsumptionOnOutput/L2/Power`
`N/${portalId}/system/0/Ac/ConsumptionOnOutput/L3/Power`

**Topics for Generator / Shore power values:**

Check number of phases:
`N/{portalId}/vebus/{vebusInstanceId}/Ac/NumberOfPhases`
Current:
`N/{portalId}/vebus/{vebusInstanceId}/Ac/ActiveIn/L1/I`
`N/{portalId}/vebus/{vebusInstanceId}/Ac/ActiveIn/L2/I`
`N/{portalID}/vebus/{vebusInstanceId}/Ac/ActiveIn/L3/I`
Voltage:
`N/{portalId}/vebus/{vebusInstanceId}/Ac/ActiveIn/L1/V`
`N/{portalId}/vebus/{vebusInstanceId}/Ac/ActiveIn/L2/V`
`N/{portalID}/vebus/{vebusInstanceId}/Ac/ActiveIn/L3/V`
Power:
`N/${portalId}/vebus/${vebusInstanceId}/Ac/ActiveIn/L1/P`,
`N/${portalId}/vebus/${vebusInstanceId}/Ac/ActiveIn/L2/P`,
`N/${portalId}/vebus/${vebusInstanceId}/Ac/ActiveIn/L3/P`

**Current implementation:**

(Skipping the prefix of the topics below, assume they start with `N/{portalId}/vebus/{vebusInstanceId}/Ac/ActiveIn/`)
* Voltage: always show L1/V
* Current: show sum of L1/I, L2/I, L3/I
* Power:  show sum of L1/P, L2/P, L3/P

**New improvements:**
Check if system is 1 phase or 3 phase.
Based on that, show the following:

For 1 phase systems:
* Voltage: L1/V
* Current: L1/I
* Power:  L1/P

For 3 phase systems:
Show values for each phase separately.
* Voltage: L1/V, L2/V, L3/V
* Current:  L1/I, L2/I, L3/I
* Power:  L1/P, L2/P, L3/P

Questions
* [x] How to determine when to show simple, one phase view vs all three phases? Right now we always show the sum of three phases; see topics above; Are these ok?
-> See comment below on what paths were used in the end.
* [x] Is it ok to use the paths above for both Generator and Shore power/Grid? Or should we look in different places based on the type of device? (e.g. under /genset/).
-> Used the same paths as before.

Pre-requisites
* [x] List of topics to use to get the data
* [x] Design/wireframe of how this should look when there is a three phase AC system

Definition of done:
* For a simple system, show AC Loads with Voltage, Current, Power (as is)
* For simulations J & K in the docker image, the system will show the data per phase (3 times Voltage, Current, Power)
* Same for Generator and Shore power boxes

**Comment by thomhos** [comment]
Implemented, needs testing and code review.

**Comment by ucorina** [comment]
Final implementation uses:
`N/${portalId}/system/0/Ac/ConsumptionOnOutput/NumberOfPhases` to determine whether to show 1 or multiple phases for the "AC Loads" box.
`N/${portalId}/vebus/${vebusInstanceId}/Ac/NumberOfPhases` to determine whether to show 1 or multiple phases for the Shore power/Generator box.

<img width="1044" alt="screenshot 2019-01-07 13 38 33" src="https://user-images.githubusercontent.com/1322468/50769338-f57aeb00-1283-11e9-88c7-b6f42579a3c1.png">
<img width="516" alt="screenshot 2019-01-07 13 44 17" src="https://user-images.githubusercontent.com/1322468/50769339-f57aeb00-1283-11e9-95ac-01013ac4c25b.png">
<img width="526" alt="screenshot 2019-01-07 13 44 21" src="https://user-images.githubusercontent.com/1322468/50769340-f57aeb00-1283-11e9-89b8-64657ce5a1af.png">

Checked with configuration A, K and L.
